/* This file is automatically generated by utils/generate-registry.pl
   Manual changes will be lost. */

#define OGLM_COUNTMAX_FogParameter 4
int oglm_count_FogParameter(int param);
#define OGLM_COUNTMAX_GetPName 16
int oglm_count_GetPName(int param);
#define OGLM_COUNTMAX_GetTextureParameter 4
int oglm_count_GetTextureParameter(int param);
#define OGLM_COUNTMAX_LightModelParameter 4
int oglm_count_LightModelParameter(int param);
#define OGLM_COUNTMAX_LightParameter 4
int oglm_count_LightParameter(int param);
#define OGLM_COUNTMAX_MaterialParameter 4
int oglm_count_MaterialParameter(int param);
#define OGLM_COUNTMAX_TextureEnvParameter 4
int oglm_count_TextureEnvParameter(int param);
#define OGLM_COUNTMAX_TextureGenParameter 4
int oglm_count_TextureGenParameter(int param);
