#!perl

use strict;
use warnings;
use OpenGL::Modern qw(
  glewCreateContext glewInit glewDestroyContext glpCheckErrors glGetString
  glGenTextures_p glBindTexture glDeleteTextures_p
  glTexImage2D_c glTexParameteri
  glGetTexLevelParameteriv_p glGetIntegerv_p
  glPixelStorei glGetTexImage_c
  glActiveTexture
  glGenFramebuffers_p glBindFramebuffer glDeleteFramebuffers_p
  glFramebufferTexture glCheckFramebufferStatus
  glViewport glClearColor glClear
  GL_FRAMEBUFFER GL_COLOR_ATTACHMENT0 GL_FRAMEBUFFER_COMPLETE
  GL_PACK_ALIGNMENT
  GL_TEXTURE_2D GL_R32F GL_RED GL_FLOAT GL_COLOR_BUFFER_BIT
  GL_TEXTURE_MIN_FILTER GL_TEXTURE_MAG_FILTER
  GL_TEXTURE1
  GL_TEXTURE_WIDTH GL_TEXTURE_HEIGHT GL_MAX_TEXTURE_SIZE GL_MAX_VIEWPORT_DIMS
  GL_TEXTURE_WRAP_S GL_TEXTURE_WRAP_T GL_NEAREST GL_CLAMP_TO_EDGE
  GL_VERSION GLEW_OK
);
use PDL;

sub with_time (&) {
  require Time::HiRes;
  my @t = Time::HiRes::gettimeofday();
  &{$_[0]}();
  printf "%g ms\n", Time::HiRes::tv_interval(\@t) * 1000;
}

print "Perl $^V OpenGL::Modern $OpenGL::Modern::VERSION PDL $PDL::VERSION\n";

my ($xdim, $ydim) = (3048, 3048);

# 4.1 core so MacOS allows >2.1
glewCreateContext(4, 1, 1, 2) == GLEW_OK or die "glewCreateContext failed";
glewInit() == GLEW_OK or die "glewInit failed";
print "OpenGL ", glGetString(GL_VERSION), "\n";
my $max_tex_dim = glGetIntegerv_p(GL_MAX_TEXTURE_SIZE);
print "Max texture dim = $max_tex_dim\n";
my $max_vp_dim = glGetIntegerv_p(GL_MAX_VIEWPORT_DIMS);
print "Max viewport dim = $max_vp_dim\n";

my ($type, $internalformat, $format) = (GL_FLOAT, GL_R32F, GL_RED);

my ($destTextureID) = glGenTextures_p(1);
with_time {
glActiveTexture(GL_TEXTURE1);
glBindTexture(GL_TEXTURE_2D, $destTextureID);
my ($dim0, $dim1) = ($xdim, $ydim);
glTexImage2D_c(GL_TEXTURE_2D, 0, $internalformat, $dim0, $dim1,
  0, $format, $type, 0);
tex_parameters();
glBindTexture(GL_TEXTURE_2D, 0);
};

my ($fbo_id) = glGenFramebuffers_p(1);
glBindFramebuffer(GL_FRAMEBUFFER, $fbo_id);
glFramebufferTexture(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, $destTextureID, 0);
my $fbstat = glCheckFramebufferStatus(GL_FRAMEBUFFER);
die "FBO Status error: " . glpErrorString(glGetError()) if !$fbstat;
die sprintf "FBO Status: %04X", $fbstat if $fbstat != GL_FRAMEBUFFER_COMPLETE;
glViewport(0,0,$xdim,$ydim);
glClearColor(-0.5, 0, 0, 0);
glClear(GL_COLOR_BUFFER_BIT);

my $p2 = zeroes(float, $xdim, $ydim);
my $skip = $p2->dim(1)-1;
my $slicearg = '-10:-1,::'.$skip;
print "Before: ", $p2->slice($slicearg), "\n";
with_time {
glBindTexture(GL_TEXTURE_2D, $destTextureID);
my ($w, $h) = map glGetTexLevelParameteriv_p(GL_TEXTURE_2D, 0, $_), GL_TEXTURE_WIDTH, GL_TEXTURE_HEIGHT;
print "Texture $w x $h\n";
glPixelStorei(GL_PACK_ALIGNMENT, 1);
glGetTexImage_c(GL_TEXTURE_2D, 0, $format, $type, $p2->address_data);
glBindTexture(GL_TEXTURE_2D, 0);
};
print "After: ", $p2->slice($slicearg);

glBindTexture(GL_TEXTURE_2D, 0);
glDeleteTextures_p($destTextureID);
glBindFramebuffer(GL_FRAMEBUFFER, 0);
glDeleteFramebuffers_p($fbo_id);

glpCheckErrors();
glewDestroyContext();

sub tex_parameters {
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
}
