name: perl
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        perl-version: ['5.16', '5.20']
        include:
          - perl-version: '5.30'
            os: ubuntu-latest
            release-test: true
            coverage: true
          - perl-version: '5.30'
            os: windows-latest
          - perl-version: '5.30'
            os: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'ci-dist: target-setup-perl'
        uses: Perl-GPU/devops/github-actions/ci-dist@main
        with:
          target-setup-perl: true
          perl-version: ${{ matrix.perl-version }}
      - name: Install dependencies
        uses: Perl-GPU/devops/github-actions/install-dep-opengl-modern-dep@main
      - name: 'ci-dist: target-all'
        uses: Perl-GPU/devops/github-actions/ci-dist@main
        with:
          target-setup-perl: false
          target-install-dist-perl-deps: true
          dist-perl-deps-configure:
            Capture::Tiny
            ExtUtils::MakeMaker::CPANfile
            Devel::CheckLib
          build-enable-graphical-display: true
          target-test-release-testing: true
          target-test: true
          test-enable-graphical-display: true
          test-enable-release-testing: ${{ matrix.release-test }}
          test-enable-coverage: ${{ matrix.coverage }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-status:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ always() }}
    needs: [ 'ci' ]
    steps:
      - uses: Perl-GPU/devops/github-actions/irc-notifications@main
        with:
          target-build-status: true
          needs: ${{ toJSON(needs) }}
