name: issue-notify

on:
  issues:
    types: [opened,assigned,closed,reopened]
  issue_comment:
    types: [created]
  pull_request:
  pull_request_review:
    types: [submitted]
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  create:
jobs:
  notify:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ always() }}
    steps:
      - uses: Perl-GPU/devops/github-actions/irc-notifications@main
        with:
          target-notifications: true
